# Generated by Django 3.1.6 on 2021-02-07 17:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredientName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ingredientQuantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IngredientPurchaseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchasedFrom', models.CharField(max_length=100)),
                ('purchasedPrice', models.CharField(max_length=100)),
                ('ingredientId', models.ForeignKey(default=uuid.UUID('96091c8b-400c-491a-aa11-76a6ce27f52b'), on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient')),
            ],
        ),
    ]
