# Generated by Django 3.1.6 on 2021-02-07 19:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientpurchasedetail',
            name='ingredientId',
            field=models.ForeignKey(default=uuid.UUID('d665c408-16e3-4a3c-af00-9c6eedbb3008'), on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient'),
        ),
    ]
