# Generated by Django 3.1.6 on 2021-02-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemPurchased', models.CharField(max_length=100)),
                ('itemDetails', models.TextField()),
                ('purchasedAt', models.FloatField()),
                ('billerName', models.CharField(max_length=100)),
                ('billedAddress', models.TextField()),
            ],
        ),
    ]
