# Generated by Django 3.1.6 on 2021-02-07 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryitem', '0003_auto_20210208_0031'),
        ('accounts', '0001_initial'),
        ('orders', '0002_auto_20210207_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='itemDetails',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='customerId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.bakeryuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='itemPurchased',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakeryitem.bakeryitem'),
        ),
    ]
